# Generated by Django 4.0.6 on 2022-07-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_userprofile_lawyer_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
